#pragma once

#define MODE_CND 1
#define MODE_MNT 2
#define MODE_PEDESTR 3

#define CONDITION_DRY 1
#define CONDITION_MOIST 2
#define CONDITION_WET 3
#define CONDITION_SLUSH 4
#define CONDITION_FROST 5
#define CONDITION_PARTLY_ICY 6
#define CONDITION_ICY 7
#define CONDITION_SNOW 8

#define TRAFFIC_NONE 0
#define TRAFFIC_NORMAL 1
#define TRAFFIC_DIFFICULT 2
#define TRAFFIC_VERY_DIFFICULT 3

#define PEDESTRIAN_NONE 0
#define PEDESTRIAN_NORMAL 1
#define PEDESTRIAN_DIFFICULT 2
#define PEDESTRIAN_PACKED_SNOW 3
#define PEDESTRIAN_FREEZING 4
#define PEDESTRIAN_WATER_AND_ICE 5
#define PEDESTRIAN_SNOW_AND_ICE 6

#define MAINTENANCE_NONE 0
#define MAINTENANCE_PLOW 1
#define MAINTENANCE_SALT 2
#define MAINTENANCE_PLOW_AND_SALT 3

#define MODE_MAINT_INPUT 1
#define MODE_NO_MAINT_INPUT 2
#define MODE_MAINT_INPUT_AND_MODEL_CHECK 3
#define MODE_MAINT_INPUT_AND_PLOUGHING_CHECK 4
#define MODE_MAINT_INPUT_AND_SALTING_CHECK 5

#define NOT_SALTY 0
#define SALTY 1

#define SALTING_REASON_NONE 0
#define SALTING_REASON_ICE 1
#define SALTING_REASON_FROST 2
#define SALTING_REASON_LIGHT_SNOW_FALL 3
#define SALTING_REASON_THAWING 4

#define NOTIFY_NONE 0
#define NOTIFY_FROST 1
#define NOTIFY_PARTLY_ICY 2
#define NOTIFY_ICY 3

#define WARNING_NONE 0
#define WARNING_FROST 1
#define WARNING_ICY 2
#define WARNING_SNOW 3
#define WARNING_SNOW_ON_COLD 4
#define WARNING_WIND 5
#define WARNING_WHIRL 6
#define WARNING_HEAVY_SNOW_FALL 7
#define WARNING_QUICK_CHANGE 8
#define WARNING_SLEETFALL_ON_ICE 9
#define WARNING_WATER_ON_ICE 10
#define WARNING_SUPERCOOLED_RAIN 11
#define WARNING_HYDROPLANING 21

