#pragma once
#define PRECIPITATION_NONE 0
#define PRECIPITATION_RAIN 1
#define PRECIPITATION_SLEET 2
#define PRECIPITATION_SNOW 3
#define PRECIPITATION_FREEZING_DRIZZLE 4
#define PRECIPITATION_FREEZING_RAIN 5
#define PRECIPITATION_HAIL 6

#define SURFACE_SNOW_DRY 1
#define SURFACE_SNOW_WET 2
